sync-images can now override the image bundle tag

diff --git a/aws_exocompute_byok_cluster/pcr/sync-images b/aws_exocompute_byok_cluster/pcr/sync-images
--- a/aws_exocompute_byok_cluster/pcr/sync-images
+++ b/aws_exocompute_byok_cluster/pcr/sync-images
@@ -41,6 +41,11 @@ while [[ $# -gt 0 ]]; do
       shift
       shift
       ;;
+    -t|--tag)
+      TAG="$2"
+      shift
+      shift
+      ;;
     -*)
       echo "Unknown command line option: $1"
       exit 1
@@ -54,7 +59,7 @@ done
 set -- "${POSITIONAL_ARGS[@]}"
 
 # Show help message and exit if required.
-if [ "$EKS_VERSION" = "" ] && [ "$NAMESPACE" = "" ] && [ "$REGISTRY" = "" ] && [ "$SERVICE_ACCOUNT" = "" ]; then
+if [ "$ABORT_ON_ECR_ERROR" = "" ] && [ "$EKS_VERSION" = "" ] && [ "$NAMESPACE" = "" ] && [ "$REGISTRY" = "" ] && [ "$SERVICE_ACCOUNT" = "" ] && [ "$TAG" = "" ]; then
   HELP="YES"
 fi
 if [ "$HELP" = "YES" ]; then
@@ -63,12 +68,13 @@ if [ "$HELP" = "YES" ]; then
   echo "Synchronize an AWS ECR registry with the latest RSC Exocompute image bundle"
   echo
   echo "Options:"
-  echo "-a, --abort-on-error    Abort when creating an ECR repository fails, ignored by default to allow for existing repositories"
+  echo "-a, --abort-on-error    Abort when creating an ECR repository fails, ignored by default to allow for existing repositories [OPTIONAL]"
   echo "-h, --help              Shows this help message"
   echo "-s, --service-account   RSC service account file [REQUIRED]"
   echo "-r, --registry          URL of ECR registry where repositories will be created (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com) [REQUIRED]"
   echo "-n, --namespace         Namespace of ECR repositories (e.g. rsc) [REQUIRED]"
   echo "-e, --eks-version       Version of the EKS cluster using the ECR registry (e.g. 1.29) [REQUIRED]"
+  echo "-t, --tag               Override the tag specified in the image bundle [OPTIONAL]"
   echo
   exit 0
 fi
@@ -116,7 +122,13 @@ elif ! images=$(printf "%s" "$result" | jq -r '.data.exotaskImageBundle.bundleIm
   printf "Failed to extract the image bundle from the GraphqQL result:\n%b\n" "$images"
   exit 1
 fi
-echo "Will read images from the $registry container registry and tag them as $tag"
+
+if [ "$TAG" == "" ]; then
+  TAG="$tag"
+  echo "Will read images from the $registry container registry and tag them as $TAG"
+else
+  echo "Will read images from the $registry container registry and tag them as $TAG (overriding the $tag bundle tag)"
+fi
 
 # Verify that we can access AWS.
 if ! output=$(aws sts get-caller-identity 2>&1); then
@@ -156,8 +168,8 @@ while read -r image; do
     exit 1
   fi
 
-  if ! output=$(docker tag "$registry/$image" "$REGISTRY/$NAMESPACE/$name:$tag" 2>&1); then
-    printf "Failed to tag the $registry/$image image as $REGISTRY/$NAMESPACE/$name:$tag:\n%b\n" "$output"
+  if ! output=$(docker tag "$registry/$image" "$REGISTRY/$NAMESPACE/$name:$TAG" 2>&1); then
+    printf "Failed to tag the $registry/$image image as $REGISTRY/$NAMESPACE/$name:$TAG:\n%b\n" "$output"
     exit 1
   fi
 done <<< "$images"
@@ -174,9 +186,9 @@ fi
 while read -r image; do
   name=$(echo "$image" | sed -e 's/:/ /g' -e 's/@/ /g' | cut -d ' ' -f1)
 
-  echo "Pushing the $REGISTRY/$NAMESPACE/$name:$tag image"
-  if ! output=$(docker push "$REGISTRY/$NAMESPACE/$name:$tag" 2>&1); then
-    printf "Failed to push the $NAMESPACE/$name:$tag image to the $REGISTRY container registry:\n%b\n" "$output"
+  echo "Pushing the $REGISTRY/$NAMESPACE/$name:$TAG image"
+  if ! output=$(docker push "$REGISTRY/$NAMESPACE/$name:$TAG" 2>&1); then
+    printf "Failed to push the $NAMESPACE/$name:$TAG image to the $REGISTRY container registry:\n%b\n" "$output"
     exit 1
   fi
 done <<< "$images"
